#!/usr/bin/env ruby
# frozen_string_literal: true

ENV["SKIP_CRUD_SETUP"] = "true"
require "rails/crud/tools/cli"

def display_help
  puts <<~HELP
    Usage: crud [command]

    Commands:
      init    Initialize by generating CRUD and config files
      gen crud    Generate CRUD file
      gen config  Generate config file
      help    Display this help message
  HELP
end

if ARGV.empty? || ARGV.include?("help")
  display_help
elsif ARGV.include?("init")
  RailsCrudTools::CLI.init
elsif ARGV == %w[gen crud]
  RailsCrudTools::CLI.generate_crud_file
elsif ARGV == %w[gen config]
  RailsCrudTools::CLI.generate_crud_config
else
  puts "Unknown command: #{ARGV.join(" ")}"
  display_help
end
